config/routes.rb
Elivewebinars::Application.routes.draw do

  root :to => 'pages#home'

  resource :pages, :only => [] do
    collection do
      get 'home'
      get 'us'
      get 'chat'
      get 'clients'
      get 'payments'
    end
  end
  
  resource :ligas, :only => [:new, :create]
  
  resource :services, :only => [] do
    collection do
      get 'webinars'
      get 'incompany'
      get 'renta'
      get 'share'
    end
  end
  
  resource :notifiers, :only => [] do
    collection do
      post 'contact'
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/ligas_controller.rb
class LigasController < ApplicationController

  http_basic_authenticate_with :name => "salvador", :password => "carlomagno"

  def new
    render 'new', :layout => false
  end

  def create
    liga = params[:liga]
    File.open('public/liga.txt', 'w') {|f| f.write(liga) }
    redirect_to '/'
  end

end

app/controllers/notifiers_controller.rb
class NotifiersController < ApplicationController

  def contact
    Notifier.contact(params[:message]).deliver
    redirect_to '/'
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @liga = File.open('public/liga.txt').read
  end
  
  def us
  end
  
  def chat
  end
  
  def clients
  end
  
  def payments
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def webinars
  end
  
  def incompany
  end
  
  def renta
  end
  
  def share
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/liga_helper.rb
module LigaHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-US">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <title>elivewebinars | Hazte webinar</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=PT+Sans+Narrow' rel='stylesheet' type='text/css'>
  
  <!-- All in One SEO Pack 1.6.8.1 by Michael Torbert of Semper Fi Web Design[256,320] -->
  <meta name="description" content="El mejor lugar para convertir tus cursos y seminarios a formato webinar!" />
  <meta name="keywords" content="seminarios en linea, seminarios online, seminarios virtuales, capacitación en linea, cursos virtuales, capacitación a distancia, webinars mexico, webinars en español, webinars latinoamérica, diseño instruccional, instructores en linea, contenidos e-learning" />
  <!-- /all in one seo pack -->
  
</head>
<body class="home blog">
<div id="main">
<%= render 'shared/menu'%>
<%= yield %>
</div>
</body>
<%= render 'shared/footer'%>
</html>

app/views/ligas/new.html.erb
<%= form_tag({:controller => "ligas", :action => "create"}, :method => "post") do %>
  <%= label_tag(:liga, "liga:") %>
  <%= text_field_tag(:liga) %>
  <%= submit_tag("Cambiar liga") %>
<% end %>

app/views/notifier/contact.text.erb
Este es un mensaje enviado desde la forma de contacto de la página
elivewebinars.com

Asunto:
<%= @message['subject']  %>

Mensaje de:
<%= @message['email']  %>

Mensaje:
<%= @message['content'] %>

app/views/pages/_all_extended.html.erb
<div class="services">
	<ul id="menu-image-menu">
    <li>
      <%= link_to('#', 'data-service' => '#webinars', 'class' => 'know-more') do %>
        <%= image_tag("elivewebinars-secciones-menu-01.png") %>
      <% end %>
      <div class="service-description webinars">
        <div class="top-divider"></div>
        <div class="tagline">Seminarios en <strong>VIVO</strong> por internet</div>
				<ul>
					<li>Seminarios a la medida</li>
					<li>Marketing de tus productos</li>
					<li>Inscripción a webinars públicos</li>
				</ul>
				<div class="learn-more">
          <%= link_to '¡Quiero saber más!', '#', 'class' => 'know-more', 'data-service' => '#webinars' %>
        </div>
        <div class="bottom-divider"></div>
      </div>
    </li>
    <li>
      <%= link_to('#', 'data-service' => '#incompany', 'class' => 'know-more') do %>
        <%= image_tag("elivewebinars-secciones-menu-03.png") %>
      <% end %>
      <div class="service-description incompany">
        <div class="top-divider"></div>
        <div class="tagline"> <strong>Transforma </strong> tu entrenamiento</div>
				<ul>
					<li>Estrategias instruccionales</li>
					<li>Soluciones de aprendizaje</li>
					<li>Formación e-learning al personal</li>
				</ul>
				<div class="learn-more">
          <%= link_to '¡Quiero saber más!', '#', 'class' => 'know-more', 'data-service' => '#incompany' %>
        </div>
        <div class="bottom-divider"></div>
      </div>
    </li>
    <li>
      <%= link_to('#', 'data-service' => '#share', 'class' => 'know-more') do %>
        <%= image_tag("elivewebinars-secciones-menu-07.png") %>
      <% end %>
      <div class="service-description share">
        <div class="top-divider"></div>
        <div class="tagline"><strong>Comparte</strong> y aprende</div>
				<ul>
          <li>Contenidos para redes sociales</li>
          <li>Portal colaborativo</li>
          <li>Aula de trabajo</li>
				</ul>
				<div class="learn-more">
          <%= link_to '¡Quiero saber más!', '#', 'class' => 'know-more', 'data-service' => '#share' %>
        </div>
        <div class="bottom-divider"></div>
      </div>
    </li>
    <li>
      <%= link_to('#', 'data-service' => '#renta', 'class' => 'know-more') do %>
        <%= image_tag("elivewebinars-secciones-menu-05.png") %>
      <% end %>
      <div class="service-description renta">
        <div class="tagline"><strong>Renta</strong> nuestros servicios</div>
				<ul>
          <li>LMS y servicios administrativos</li>
          <li>Contenidos para LMS</li>
          <li>Extensiones</li>
				</ul>
				<div class="learn-more">
          <%= link_to '¡Quiero saber más!', '#', 'class' => 'know-more', 'data-service' => '#renta' %>
        </div>
      </div>
    </li>
  </ul>
</div> 

app/views/pages/_incompany.html.erb
<div id="content_padding">
  <div id="content">
    <div class="container incompany">
      <div class="column-1">
        <h3><b>elive</b> Incompany</h3>

        <div class="text1">
          <strong class="heading">
          Ponemos a su disposición nuestros servicios de consultoría en estrategias instruccionales y tecnología educativa con la finalidad de colaborar en la optimización de los diferentes procesos de capacitación y comunicación en su organización</strong>
        </div>
        
        <h4>Productos y Servicios INCOMPANY</h4>
        
        <div class="text1">
        Nuestra experiencia se ve reflejada en el desarrollo e implementación de los productos y servicios que ponemos a su disposición:
        </div>
        
        <ul class="list">
          <li><span>1</span><a><b>Consultoría</b><i>Servicios de consultoría en estrategias instruccionales</i></a></li>
          <li><span>2</span><a><b>Elaboración de contenidos</b><i>Temáticos e instruccionales</i></a></li>
          <li><span>3</span><a><b>Asesoría de diseño instruccional</b><i>En el desarrollo de tus contenidos de capacitación</i></a></li>
          <li><span>4</span><a><b>Mantenimiento</b><i>De productos instruccionales, cursos  y materiales de capacitación</i></a></li>
          <li><span>5</span><a><b>Blended e-learning</b><i>Programas de capacitación blended e-learning</i></a></li>
        </ul>
        <br />
        
        <h4>Programa de Formación de Instructores <b>y Desarrolladores de Contenidos</b></h4>
        <div class="text1">
        Formación y entrenamiento en Innovación educativa, estrategias y técnicas e-learning y presenciales
        </div>

      </div>

      <div class="column-2">
        
        <h4>Desarrollo de Contenidos y Servicios Curriculares</h4>
        
        <div class="text1">
        Nuestros servicios tienen como finalidad transformar y sacar provecho del capital intelectual y el conocimiento propio de la empresa. Nuestro proceso incluye:
        </div>
        
        <ul class="incompany-checked">
          <li>Iniciar cada compromiso con una evaluación diagnóstica estratégica</li>
          <li>Identificar y recopilar la información y los contenidos de aprendizaje requeridos alineados a las necesidades del negocio</li>
          <li>Aplicar nuestra probada metodología de desarrollo instruccional para el desarrollo de contenidos</li> 
          <li>Entregar contenidos a tiempo, dentro del presupuesto y con objetivos y enfoque claros a través de aplicar una rigurosa administración del proyecto</li>
        </ul>
        
        <br />
        <%= image_tag('incompany-1.png')%>


      </div>
    </div>
  </div>
</div>

app/views/pages/_renta.html.erb
  <div id="content_padding">
    <div id="content">
      <div class="container renta">
        <div class="column-1">
          <h3><b>elive</b>RENTA</h3>
          
           <div class="text1">
            <strong class="heading">LE OFRECE LA IMPLEMENTACIÓN DE PLATAFORMA DE CAPACITACIÓN Y CONTENIDOS MULTIMEDIA PARA LMS</strong>
          </div>
          
          <h4>LMS</h4>

          <div class="text1">
          Es la solución que le permite entregar sus contenidos de capacitación y llevar un seguimiento de avance y desempeño de sus participantes de una manera  óptima a través de evaluaciones y generación de reportes.  
          </div>
          
          <div class="text1">
          Nuestra plataforma de entrenamiento <em>LMS</em> es robusta y compatible con las normas <em>SCORM</em> y <em>AICC</em>, además le permite accesos seguros; puede inscribir tantos participantes como su estrategia de capacitación lo requiera. Pregunte por nuestra opción a renta. 
          </div>
          
          <div class="text1">Contamos con extensiones para:</div>
          
          <ul class="tag">
            <li>Aulas Virtuales</li>
            <li>Redes Sociales</li>
            <li>Wikis</li>
            <li>Bibliotecas</li>
            <li>Foros</li>
            <li>Blogs</li>
          </ul>

        </div>

        <div class="column-2">
          
          <h3><b>Nuestros productos y servicios incluyen:</b></h3>

          <ul class="list">
            <li><span>1</span><a><b>Asesoría Instruccional para el diseño de contenidos</b></a></li>
            <li><span>2</span><a><b>Entrega Rápida</b></a></li>
            <li><span>3</span><a><b>Personalización de la plataforma</b></a></li>
            <li><span>4</span><a><b>Servicios de soporte 24/7</b></a></li>
            <li><span>5</span><a><b>Servicios administrativos de capacitación</b></a></li>
            <li><span>6</span><a><b>Capacitación para su manejo</b></a></li>
          </ul>
          <p>Nota: No requiere licencia de uso</p>
          <br />
           
          <%= image_tag("renta-1.jpg")%>  
        
        </div>
      </div>
    </div>
  </div>

app/views/pages/_share.html.erb
  <div id="content_padding">
    <div id="content">
      <div class="container share">
        <div class="column-1">
          <h3><b>elive</b>SHARE</h3>
          
          <!--div class="explanations">
           ?Que es? | Porque | Juan escutia | Lady Gaga
          </div-->

          <div class="text1">
            <strong class="heading">
            Ofrece redes estratégicas de comunicación entre los equípos de trabajo y los lideres que laboran en proyectos particulares de la organización. Ideal para informar, entrenar, documentar y motivar el logro de metas de manera transparente</strong>
          </div>
          
          <h4>Diseño de Contenidos Multimedia</h4>
          
          <div class="text1">
          La fuerza de trabajo debe tener acceso a contenido informal  y formal de aprendizaje el cual es relevante para que el personal se mantenga motivado, informado,  y sobre todo competente para llevar a cabo sus actividades laborales con excelencia.
          </div>
          
          <ul class="tag">
            <li>Contenidos Rapid Learning</li>
            <li>Videos</li>
            <li>Podcasts</li>
            <li>Articulos</li>
            <li>Presentaciones Power Point</li>
            <li>e-books</li>
            <li>Wikis</li>
            <li>Evaluaciones</li>
            <li>Ejercicios Prácticos</li>
            <li>PDFs</li>
            <li>Guias rápidas</li>
            <li>Manuales Operativos</li>
            <li>Cursos e-learning</li>
            <li>Blogs</li>
          </ul>
          <br />
          <%= image_tag("share-1.png")%>
        </div>

        <div class="column-2">
          <h4>Plataforma de Entrenamiento y Colaboración Estratégica</h4>
          
          <div class="text1">
          Se implementa en proyectos específicos de negocio en los cuales se involucran el grupo de aprendices y el grupo de facilitadores como mentores, instructores y líderes de proyectos  quienes interactúan en una interface o portal social que puede ser monitoreada por los administradores del proyecto.
          </div>
          
          <div class="text1">
          Este portal está diseñado especialmente para lograr los objetivos de los grupos involucrados, que a su vez atienden a los objetivos de negocio y a la valiosa documentación de la experiencia. El diseño de las actividades interactivas y de aprendizaje se desarrollan estratégicamente tanto en su capacitación como en su seguimiento. El programa varía en duración y los participantes tienen acceso a:
          </div>

          <ul class="list">
            <li><span>1</span><a>Seminarios, Talleres y Reuniones en VIVO por Internet</a></li>
            <li><span style="float: left;">2</span><a>Foros efectivos para compartir buenas prácticas, opiniones y contenidos relevantes</a></li>
            <li><span>3</span><a>Acceso a materiales multimedia atractivos que incluyen evaluación</a></li>
            <li><span>4</span><a>Twitters relevantes y contextualizados</a></li>
            <li><span>5</span><a>Etiquetas sociales particulares según el programa en el que participa</a></li>
          </ul>
          <br /><br />
          <h4>Aula Virtual de Trabajo</h4>
          
          <div class="text1">
          Es la solución que le permite llevar a cabo sus reuniones de trabajo con sus colegas, proveedores, y otros miembros de la organización en el momento en que usted lo desee.   Utilice esta opción si lo que necesita es informar, revisar y elaborar contenidos, capacitar de forma breve, intercambiar documentos, crear contenidos, revisar soluciones, etc.
          </div>

        </div>
      </div>
    </div>
  </div>

app/views/pages/_webinars.html.erb
  <div id="content_padding">
    <div id="content">
      <div class="container webinars">
        <div class="column-1">
          <h3><b>elive</b>Webinars</h3>
          

          <div class="text1">
             <strong class="heading">LOS WEBINARS SON SEMINARIOS O PRESENTACIONES EN VIVO POR INTERNET, IDEALES PARA CAPACITAR O PROMOVER PRODUCTOS Y SERVICIOS POR EXPERTOS CONSULTORES.  LOS WEBINARS SON ACCESADOS DESDE LA COMODIDAD DE CASA U OFICINA POR SU COMPUTADORA, TABLET O SMARTPHONE</strong>
          </div>
          
          <h3><b>Tipos de WEBINARS:</b></h3>
        
          <h4>Marketing</h4>
          
          <div class="text1">
             Transforme sus sesiones presenciales en eventos virtuales y acérquese a sus clientes y prospectos con la mejor tecnología de promoción directa sin gastar en viáticos. Aumente el prestigio de su compañía, la lealtad de sus clientes donde quiera que ellos se encuentren, y sea usted, y  sus expertos líderes de venta, quienes directamente y con pasión, lleguen al mercado potencial con el mensaje clave e intensidad precisas.
          </div>
          

          <h4>Públicos</h4>
          
          <div class="text1">
             Capacítese directamente con el experto en el tema o habilidad de su preferencia y aprenda en pocas horas lo que debe aplicar en forma inmediata en su trabajo. Los webinars públicos son seminarios programados periódicamente  y son ofrecidos al público en general.  La capacitación se desarrolla en un ambiente virtual dinámico, y ofrece ventajas equivalentes a las que ofrece un seminario presencial, a diferencia de que los contenidos son más breves por su enfoque a solución. Nuestra capacitación pública  se apega estrictamente a la descripción y objetivos de aprendizaje ofrecidos desde la venta. 
          </div>
          
          <div class="block2">
					  <a href="<%= liga %>" title="Conctacto" target="_blank">Inscribase a nuestros WEBINARS públicos</a>
						<p class="padding1">&nbsp;</p>
						<p class="padding1">&nbsp;</p>
				  </div>
				  
				  <div class="link">
            <a href="services/webinars" class="wiki"><span><span>Más información</span></span></a>
          </div>
          
        </div>
        <div class="column-2">
          
          <h4>A la Medida</h4>
          <div class="text1">
             Nuestro servicio de capacitación privada está orientado a dar apoyo a las empresas que necesitan informar sobre una actualización, asistir en el desarrollo de competencias laborales que agreguen valor a los procesos de negocio o motivar a la acción con este mismo propósito.  Cada plan privado de capacitación puede ser desarrollado e implementado bajo las siguientes modalidades.
          </div>
          
          De clic en cada producto para ver su descripción<br /><br />
          
          <ul class="list">
            <li><span>1</span><a href="#" class="information">Webinar Actualización</a>
            <i class="information">: Optima si lo que busca es informar sobre ajustes a la fecha, y vigencias, adaptaciones y cambios relativos a procesos, normas, leyes, recurso, sistemas y otros elementos de negocio,  a sus empleados y colaboradores.</i></li>
            
            <li><span>2</span><a href="#" class="information">Webinar Curso</a><i class="information"> 
            : Si requiere habilitar a sus empleados  en el dominio de alguna tarea, actividad, o área de conocimiento específica de manera puntual, breve y efectiva.</i></li>

            <li><span>3</span><a href="#" class="information">Webinar Taller</a><i class="information">: Este formato de entrenamiento es ideal para que los participantes,  a través de reuniones virtuales que también se llaman talleres, descubran o construyan de forma colaborativa soluciones de negocio, establecer consensos, intercambiar experiencias, se motiven a la acción, o logren cualquier objetivo o meta de equipo.</i></li>

            <li><span>4</span><a href="#" class="information">Webinar Conferencia</a><i class="information">: Si su propósito es informar y/o motivar a la acción a sus empleados, proveedores o clientes de manera directa  o a través de un tercero experto en la materia, de manera rápida y efectiva, esta solución es la indicada para usted.</i></li>

            <li><span>5</span><a href="#" class="information">Webinar Catálogo</a><i class="information">: Le ofrecemos una lista de temas de webinars con enfoque a solución. Cada webinar tiene una duración de 3 horas. ¡Pregunte por nuestro catálogo!</i></li>

            <li><span>6</span><a href="#" class="information">Webinar Catálogo Adhoc</a><i class="information">: De la lista de temas de curso de nuestro catálogo, le ofrecemos adaptar sus contenidos: ejercicios, ejemplos y escenarios  según el contexto y  requerimiento de sus participantes,  hasta en un 25%. ¡Seleccione el que más le convenga!</i></li>
            
          </ul>
          <br />
          <div class="block1">
					  <a href="#" title="Conctacto">Solicite catálogo elive WEBINARS</a>
						<p class="padding1">Pregunte por las modalidades de audiencia  webinar: Masivo 100™, Grupo 22™ y Equipo 5™</p>
				  </div>
          
          <br /><br />
          <!--
          <cite>I am so impressed with your services ... I really, really am
          shocked to finally have some great information from an expert.</cite>

          <div class="text2">
            Melanie P. <a href="#" title="Thailand Detox">Thailand Detox</a><br />
            <a href="#" title="Testimonials">Read more testimonials</a>
          </div>
          -->
          
          <%= image_tag('webinars-1.png')%>

        </div>
      </div>
    </div>
  </div>

app/views/pages/chat.html.erb
<%= render 'shared/banner'%>

app/views/pages/clients.html.erb
<%= render 'shared/banner'%>

app/views/pages/home.html.erb
<%= render 'shared/banner'%>
<%= render 'all_extended' %>
<div id="webinars" class="service">
  <%= render 'webinars', :liga => @liga %>
</div>
<div id="incompany" class="service">
  <%= render 'incompany' %>
</div>
<div id="renta" class="service">
  <%= render 'renta' %>
</div>
<div id="share" class="service">
  <%= render 'share' %>
</div>

app/views/pages/payments.html.erb
<%= render 'shared/banner'%>

app/views/pages/us.html.erb
<%= render 'shared/banner'%> 
<div class="explanation no-padding">

  
  <div class="question">
    <h3 id="q-1">¿Quiénes somos?</h3>
    <table>
      <tr>
        <td>
          <p>Comprometidos en llevar a su empresa servicios y productos de capacitación innovadores y efectivos, acordes a la tendencia del mercado mundial actual, se ha creado la empresa Capacitación elive</p>
          <p>
          Capacitación elive es una organización experta en la aplicación de servicios de estrategias instruccionales e-learning  para el análisis, procesamiento, elaboración y entrega efectiva de contenidos especializados que generen valor de negocio en las áreas de:
          </p>
           <ul>
            <li>Capacitación del personal y asociados de una empresa</li>
            <li>Ventas y Marketing para la efectiva presentación de las soluciones empresariales 
      (productos y servicios ) de una organización a sus clientes y prospectos.</li>
          </ul>
        </td>
        <td>
          <p>
          Nuestra empresa  fundamenta su estrategia de servicios para atender los requerimientos del cliente en un modelo integral de solución óptimo y congruente de acuerdo a sus necesidades e infraestructura equilibrando sus elementos fundamentales:
          </p>
          <br />
          <%= image_tag('us-1.jpg', :style => "display:block;margin:auto;")%>
        </td>
      </tr>
    </table>
    
    <br />
  </div>
  
</div>

app/views/services/_all_compressed.html.erb
<div class="services-small">
    <ul id="menu-image-menu">
      <li>
        <%= link_to '/' do %>
          <%= image_tag('elivewebinars-secciones-menu-01.png')%>
        <% end %>
      </li>
      <li>
        <%= link_to '/' do %>
          <%= image_tag('elivewebinars-secciones-menu-03.png')%>
        <% end %>
      </li>
      <li>
        <%= link_to '/' do %>
          <%= image_tag('elivewebinars-secciones-menu-05.png')%>
        <% end %>
      </li>
      <li>
        <%= link_to '/' do %>
          <%= image_tag('elivewebinars-secciones-menu-07.png')%>
        <% end %>
      </li>
    </ul>
</div>

app/views/services/renta.html.erb
<%= render 'shared/renta_banner'%> 
<div class="renta explanation">
  <div class="question-list">
    <ul>
      <li><a href='#q-1'>¿Qué es elive RENTA</a></li>
    </ul>
  </div>
  
  <div class="question">
    <h3 id="q-1">¿Qué es elive RENTA?</strong></h3>
    <p>Es la solución que le permite de una manera fácil y rápida migrar o transformar sus cursos presenciales y promoción de sus productos y servicios a formato WEBINAR.</p>
    <p>Nuestros productos y servicios incluyen:</p>
    <ul>
      <li><strong>Solución<em> elivewebinars</em></strong> incluye acompañamiento/moderación del evento</li>
      <li><strong>Asesoría Instruccional</strong> para el diseño de contenidos</li>
      <li><strong>Locación de trasmisión del evento</strong> ,asesoría y/o renta de locación</li>
    </ul>
    <p>Los beneficios que usted puede obtener al transmitir sus eventos en formato <strong><em>elivewebinar</em></strong> son:</p>
    <ul>
      <li>Audio de presentador y participantes</li>
      <li>Video de presentador y participantes</li>
      <li>Sección de chat</li>
      <li>Sección de materiales Power Point</li>
      <li>Compartir Pantalla</li>
      <li>Grupos pequeños de trabajo</li>
      <li>Descargar documentos</li>
      <li>Lista de asistentes e interacción en salón virtual a través de íconos</li>
      <li>Evaluaciones y encuestas</li>
      <li>Envío de ligas y recordatorio del evento</li>
    </ul>
    <p>Capacite o promueva sus productos y servicios en grupos masivos o particulares</p>
  </div>
  
  <div id="ovni"></div>​
  
</div>

app/views/shared/_footer.html.erb
<div id="footer"> 
	<div class="center">
	  <div class="footer_widget"> 
	    <h4>NOTICIAS</h4>
	      <div class="foot-info" id="scroller">
	        <ul id="tweets">
	        </ul>
	      </div>
	  </div><!--footerwidget-->
	  <div class="footer_widget">
	   <h4>¿TE QUEDARON DUDAS?</h4>
	   <ul>
	     <div class="foot-info">
	       <%= form_tag(contact_notifiers_path) do%>
	         <label>Asunto:</label>
	         <input type='text' name='message[subject]' /><br/>
	         <label>Email:</label>
	         <input type='text' name='message[email]'/><br/>
	         <label>Mensaje:</label>
	         <textarea name='message[content]'></textarea>
	         <input type="submit" value="Enviar"></input>
	       <% end %>
	     </div>
	   </ul>
	  </div><!--footerwidget-->
	  <div class="footer_widget">
	    <h4>Contacto</h4>
	    <ul id="list-footer-connect">
        <li><a href="http://twitter.com/elivewebinars" target="_blank" id="footer-twitter"><span class="icon-footer-twitter"></span>Síguenos en Twitter</a></li>
        <li><a href="#" target="_blank" id="footer-twitter"><span class="icon-footer-phone"></span>+52 81 81295745</a></li>
        <li><a href="#" target="_blank" id="footer-twitter"><span class="icon-footer-mail"></span>madya.ayala@elivewebinars.com</a></li>
        <% if false%>
        <li><a href="#" id="footer-blog"><span class="icon-footer-blog"></span>Lee nuestro blog</a></li>
        <li><a href="#" id="footer-team"><span class="icon-footer-team"></span>Sobre nosotros</a></li>
        <li><a href="#" id="footer-jobs"><span class="icon-footer-work"></span>Contactanos</a></li>
        <% end %>
      </ul>
	  </div><!--footerwidget-->
	</div><!--center-->
</div>

<script>
  $('#scroller').newsScroller({speed:800,pause:4e3,animation:"fade",direction:"up",mousePause:!0,showItems:6})
</script>

app/views/shared/_incompany_banner.html.erb
<div id="top_section">
  <div id="photos" >
    <img alt="Los mejores seminarios de capacitación y difución de sus productos y servicios en vivo por la internet." src="/assets/banner-5.jpg" >
  </div>
	<div class="incompany slogan">
		<h2>¡hazte <strong>webinar!</strong></h2>
		<div id="caption">
		</div>
	</div>
</div>
<%= render 'services/all_compressed'%>

app/views/shared/_menu.html.erb
<div id="high"></div>
<div id="header">
	<div class="top">
		<ul class="menu">
      <li><a  href="/" title="Inicio">Inicio</a></li>
			<li><%= link_to "Nosotros" ,us_pages_path%></li>
      <li><%#= link_to "Chat en Linea" ,chat_pages_path, :class => 'large'%></li>
      <li><%#= link_to "Clientes", clients_pages_path%></li>
			<li><%#= link_to "Formas de Pago" , payments_pages_path, :class => 'large'%></li>
			<li><%= link_to "Requerimientos" ,'/requerimientos.pdf', :class => 'large'%></li>
		</ul>
		<h5 class="logo"><a href="/" title="Hazte webinar">elive webinars</a></h5>
	</div>
</div>